# ── Dockerfile ────────────────────────────────────────────────────────────────
# Builds a container for the Newsgroups Semantic Search FastAPI service.
#
# Design decisions:
# - python:3.10-slim: matches our dev environment exactly, slim keeps
#   image size small (~150MB base vs ~900MB for full python:3.10)
# - Pre-built artifacts (embeddings/ and models/) are copied into the image.
#   This means the container starts instantly — no re-embedding 18k docs.
# - The sentence-transformers model is downloaded at build time (not runtime)
#   so the container has zero external dependencies when running.
# - Uvicorn runs on 0.0.0.0:8000 to accept connections from outside container.
# - Non-root user for security best practice.

FROM python:3.10-slim

# ── System dependencies ────────────────────────────────────────────────────────
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# ── Working directory ──────────────────────────────────────────────────────────
WORKDIR /app

# ── Install Python dependencies ────────────────────────────────────────────────
# Copy requirements first (layer caching — only reinstalls if requirements change)
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# ── Pre-download the sentence-transformers model ───────────────────────────────
# Downloads at build time so the container has no external deps at runtime
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

# ── Copy application code ──────────────────────────────────────────────────────
COPY app/ ./app/

# ── Copy pre-built artifacts ───────────────────────────────────────────────────
# These are generated by the scripts/ pipeline and must exist before building
COPY embeddings/ ./embeddings/
COPY models/     ./models/

# ── Non-root user ──────────────────────────────────────────────────────────────
RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
USER appuser

# ── Expose port ────────────────────────────────────────────────────────────────
EXPOSE 8000

# ── Start server ───────────────────────────────────────────────────────────────
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]